### ISSUE TITLE
Wrong year in version number of latest release tag

### ISSUE THREAD

**Issue by vutny** [saltstack/salt-testing#115]
Hi @s0undt3ch . It appears that the year number in the latest release tag for 9a45326 is wrong.
I guess it should be `v2017.2.20` instead of `v2016.2.20`. Only the git tag name has the mistake.
It seems affect only releases page on GitHub though.

**Comment by s0undt3ch** [comment]
Bah! I'll fix it. It was late ;)

**Comment by s0undt3ch** [comment]
Deleted the old tag and pushed the new one.

**Comment by s0undt3ch** [comment]
Thanks!
